version: '3.0'

volumes:
  redis-data:
  postgres-db-volume:

services:
  kafka:
    restart: always
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    depends_on:
      - zookeeper
  postgres:
    restart: always
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
  redis:
    restart: always
    image: bitnami/redis:7.0
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
  zookeeper:
    restart: always
    image: "zookeeper:3.8.0"
    ports:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
      ZOO_ADMINSERVER_ENABLED: "false"
  tb-js-executor:
    restart: always
    image: "thingsboard/tb-js-executor:3.4.4"
    deploy:
      replicas: 2
    env_file:
      - tb-js-executor.env
      - queue-kafka.env
  tb-core1:
    restart: always
    image: "thingsboard/tb-node:3.4.4"
    ports:
      - "8080"
      - "7070"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-core1
      TB_SERVICE_TYPE: tb-core
      EDGES_ENABLED: "true"
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
      - cache-redis.env
      - tb-node.postgres.env
      - queue-kafka.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-logs:/var/log/thingsboard
    depends_on:
      - redis
      - zookeeper
      - tb-js-executor
      - tb-rule-engine1
      - tb-rule-engine2
      - postgres
      - kafka
  tb-core2:
    restart: always
    image: "thingsboard/tb-node:3.4.4"
    ports:
      - "8080"
      - "7070"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-core2
      TB_SERVICE_TYPE: tb-core
      EDGES_ENABLED: "true"
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
      - cache-redis.env
      - tb-node.postgres.env
      - queue-kafka.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-logs:/var/log/thingsboard
    depends_on:
      - redis
      - zookeeper
      - tb-js-executor
      - tb-rule-engine1
      - tb-rule-engine2
      - postgres
      - kafka
  tb-rule-engine1:
    restart: always
    image: "thingsboard/tb-node:3.4.4"
    ports:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-rule-engine1
      TB_SERVICE_TYPE: tb-rule-engine
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
      - cache-redis.env
      - tb-node.postgres.env
      - queue-kafka.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-logs:/var/log/thingsboard
    depends_on:
      - redis
      - zookeeper
      - tb-js-executor
      - postgres
      - kafka
  tb-rule-engine2:
    restart: always
    image: "thingsboard/tb-node:3.4.4"
    ports:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-rule-engine2
      TB_SERVICE_TYPE: tb-rule-engine
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
      - cache-redis.env
      - tb-node.postgres.env
      - queue-kafka.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-logs:/var/log/thingsboard
    depends_on:
      - redis
      - zookeeper
      - tb-js-executor
      - postgres
      - kafka
  tb-mqtt-transport1:
    restart: always
    image: "thingsboard/tb-mqtt-transport:3.4.4"
    ports:
      - "1883"
    environment:
      TB_SERVICE_ID: tb-mqtt-transport1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-mqtt-transport.env
      - cache-redis.env
      - queue-kafka.env
    volumes:
      - ./tb-transports/mqtt/conf:/config
      - ./tb-transports/mqtt/log:/var/log/tb-mqtt-transport
    depends_on:
      - redis
      - zookeeper
      - tb-core1
      - tb-core2
      - kafka
  tb-mqtt-transport2:
    restart: always
    image: "thingsboard/tb-mqtt-transport:3.4.4"
    ports:
      - "1883"
    environment:
      TB_SERVICE_ID: tb-mqtt-transport2
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-mqtt-transport.env
      - cache-redis.env
      - queue-kafka.env
    volumes:
      - ./tb-transports/mqtt/conf:/config
      - ./tb-transports/mqtt/log:/var/log/tb-mqtt-transport
    depends_on:
      - redis
      - zookeeper
      - tb-core1
      - tb-core2
      - kafka
  tb-http-transport1:
    restart: always
    image: "thingsboard/tb-http-transport:3.4.4"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-http-transport1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-http-transport.env
      - cache-redis.env
      - queue-kafka.env
    volumes:
      - ./tb-transports/http/conf:/config
      - ./tb-transports/http/log:/var/log/tb-http-transport
    depends_on:
      - redis
      - zookeeper
      - tb-core1
      - tb-core2
      - kafka
  tb-http-transport2:
    restart: always
    image: "thingsboard/tb-http-transport:3.4.4"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-http-transport2
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-http-transport.env
      - cache-redis.env
      - queue-kafka.env
    volumes:
      - ./tb-transports/http/conf:/config
      - ./tb-transports/http/log:/var/log/tb-http-transport
    depends_on:
      - redis
      - zookeeper
      - tb-core1
      - tb-core2
      - kafka
  tb-web-ui1:
    restart: always
    image: "thingsboard/tb-web-ui:3.4.4"
    ports:
      - "8080"
    env_file:
      - tb-web-ui.env
  tb-web-ui2:
    restart: always
    image: "thingsboard/tb-web-ui:3.4.4"
    ports:
      - "8080"
    env_file:
      - tb-web-ui.env
  tb-vc-executor1:
    restart: always
    image: "thingsboard/tb-vc-executor:latest"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-vc-executor1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-vc-executor.env
      - cache-redis.env
      - queue-kafka.env
    volumes:
      - ./tb-vc-executor/conf:/config
      - ./tb-vc-executor/log:/var/log/tb-vc-executor
    depends_on:
      - redis
      - zookeeper
      - tb-core1
      - tb-core2
      - kafka
  tb-vc-executor2:
    restart: always
    image: "thingsboard/tb-vc-executor:latest"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-vc-executor2
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-vc-executor.env
      - cache-redis.env
      - queue-kafka.env
    volumes:
      - ./tb-vc-executor/conf:/config
      - ./tb-vc-executor/log:/var/log/tb-vc-executor
    depends_on:
      - redis
      - zookeeper
      - tb-core1
      - tb-core2
      - kafka
  haproxy:
    restart: always
    container_name: "${LOAD_BALANCER_NAME}"
    image: thingsboard/haproxy-certbot:1.5.0
    volumes:
     - ./haproxy/config:/config
     - ./haproxy/letsencrypt:/etc/letsencrypt
     - ./haproxy/certs.d:/usr/local/etc/haproxy/certs.d
    ports:
     - "80:80"
     - "443:443"
     - "1883:1883"
     - "7070:7070"
     - "9999:9999"
    cap_add:
     - NET_ADMIN
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      MQTT_PORT: 1883
      EDGES_RPC_PORT: 7070
      FORCE_HTTPS_REDIRECT: "false"
    links:
        - tb-core1
        - tb-core2
        - tb-web-ui1
        - tb-web-ui2
        - tb-mqtt-transport1
        - tb-mqtt-transport2
        - tb-http-transport1
        - tb-http-transport2
